# Basic Site Settings
locale: "en-US"
title: "Abhay / Portfolio"
title_separator: "-"
name: &name "AbhayBhandarkar"
description: &description "Aspiring researcher and developer with a focus on Artificial Intelligence, Machine Learning and Deep Learning in Aeronautical, Aerospace and Robotic applications"
url: https://abhaybhandarkar.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "AbhayBhandarkar/abhaybhandarkar.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
author:
  # Biographic information
  avatar: "profile.png"
  name: "Abhay"
  pronouns: "he/him"
  bio: "Aspiring researcher and developer with a focus on Artificial Intelligence, Machine Learning and Deep Learning in Aeronautical, Aerospace and Robotic applications"
  location: "India"
  employer: "Undergraduate Student"
  uri: # URL (Optional)
  email: "abhaybhandarkar@gmail.com" 

  # Academic websites
  arxiv: # URL (Optional)
  googlescholar: "https://scholar.google.com/citations?user=hFilxmsAAAAJ&hl=en"
  orcid: "http://orcid.org/yourorcidurl"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=abhay+example"
  researchgate: # URL (Optional)

  # Repositories and software development
  github: "https://github.com/AbhayBhandarkar"
  kaggle: "your-kaggle-username"  
  stackoverflow: "your-stackoverflow-username"

  # Social media
  linkedin: "www.linkedin.com/in/abhaybhandarkar"
  twitter: "your-twitter-username" # X / Twitter

# Site Settings
teaser: "teaser-image.png" # filename of teaser fallback image placed in /images/
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"

atom_feed:
  hide: false

# SEO Related
google_site_verification: "your-google-site-verification-code"
bing_site_verification: "your-bing-site-verification-code"

# Social Sharing
twitter:
  username: &twitter "your-twitter-username"

# Analytics
analytics:
  provider: "google-analytics-4"
  google:
    tracking_id: "your-google-analytics-tracking-id"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
